# Generated by Django 3.2.9 on 2021-12-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
