# Generated by Django 3.2.9 on 2021-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20211211_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='account_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
