# Generated by Django 3.2.9 on 2021-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
