# Generated by Django 3.2.9 on 2021-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_alter_cart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='aadhaar_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='account_address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='farmer_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
