# Generated by Django 3.2.9 on 2021-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0009_auto_20211214_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_ids',
            field=models.TextField(default=''),
        ),
    ]
