# Generated by Django 3.2.9 on 2021-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_orders_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buyer_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='seller_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
